### PR TITLE
User can create an entry

### PR DESCRIPTION
**Pull request by adrienne-yung**
code-journal-feature-1 2 pic

### CODE REVIEW

**Comment by adrienne-yung** [comment]
code-journal-feature-1 3 pic

**Comment by adrienne-yung** [comment]
code-journal-feature-1 4 pic

**Comment by adrienne-yung** [comment]
code-journal-feature-1 5 pic

**Comment by adrienne-yung** [comment]
code-journal-feature-1 6 pic

**Comment by adrienne-yung** [comment]
code-journal-feature-1 7 pic

**Review by codingcodymiller — APPROVED** [review]

**Pull request merged**
